---

- hosts: localhost
  gather_facts: true
  become: yes

  vars:
    ntp_servers:
      - 0.amazon.pool.ntp.org
      - 1.amazon.pool.ntp.org
      - 2.amazon.pool.ntp.org
      - 3.amazon.pool.ntp.org
    cis_level_1_exclusions:
    # Allows packer scripts to build by enabling /tmp
    #  - 1.1.2
    #  - 1.1.3
    #  - 1.1.4
    #  - 1.1.5
    # Firewall rules and locks us out at a point
      - 3.3.2   # Ensure /etc/hosts.allow is configured
      - 3.3.3   # Check if /etc/hosts.deny configuration file exists
      - 3.5.1.1 # Ensure default deny firewall policy(DROP INPUT)
      - 3.5.1.4 # Ensure firewall rules exist for accepting SSH connections
      - 3.5.2.1 # Ensure IPv6 default deny firewall policy

    cis_level_2_exclusions:
      - 6.1.1   # Audit system file permissions 
      - 1.6.1.1 # Install and ensure SELinux is not disabled 
      - 1.6.1.2 # Setup selinux
      - 1.6.1.3 # Setup selinux
      - 1.6.1.4 # Ensure SETroubleshoot is not installed (Scored)
      - 1.6.2   # Install the SE Linux requirements - libselinux
      - 3.6     # Ensure that IPv6 is disabled
      - 4.1.1.2 # Ensure system is disabled when audit logs are full
      #- 4.1.2   # Ensure auditd service is enabled (Scored)
      - 4.1.3   # Update grub with audit enabled
      - 4.1.4   # Ensure events that modify date and time information are collected (Scored)
      - 4.1.5   # Ensure events that modify user/group information are collected(Scored) - auditd
      - 4.1.6   # Ensure events that modify the system's network environment are collected(Scored) - auditd
      - 4.1.7   # Ensure events that modify the system's Mandatory Access Controls are collected(Scored) - auditd
      - 4.1.8   # Ensure login and logout events are collected(Scored) - auditd
      - 4.1.9   # Ensure session initiation information is collected (Scored) - auditd

  roles:
    - AmazonLinux2-Hardening-Ansible
