---

- hosts: localhost
  gather_facts: true
  become: yes

  vars:
    ntp_servers:
      - 0.amazon.pool.ntp.org
      - 1.amazon.pool.ntp.org
      - 2.amazon.pool.ntp.org
      - 3.amazon.pool.ntp.org
    cis_level_1_exclusions:
    # Allows packer scripts to build by enabling /tmp
    #  - 1.1.2
    #  - 1.1.3
    #  - 1.1.4
    #  - 1.1.5
     # Allows packer scripts to build by enabling /tmp
      - 1.1.2
      - 1.1.3
      - 1.1.4
      - 1.1.5
      - 1.1.15 # nsure nodev option set on /dev/shm partition
      - 1.1.16 # Ensure nosuid option set on /dev/shm partition
      - 1.1.17 # Ensure noexec option set on /dev/shm partition
      - 
      - 2.1.1.2
    # Firewall rules and locks us out at a point
      - 3.1.1
      - 3.3.2
      - 3.3.3
      - 3.5.1.1
      - 3.5.1.4
      - 3.5.2.1
      - 3.5.2.2
      - 4.2.1.1
      - 5.1.1
      - 5.2.13
      - 5.2.14
      - 5.2.15
      - 5.2.16
      - 5.2.17
      - 5.2.18
      - 5.2.19
    # Firewall rules and locks us out at a point
      - 3.3.2   # Ensure /etc/hosts.allow is configured
      - 3.3.3   # Check if /etc/hosts.deny configuration file exists
      - 3.5.1.1 # Ensure default deny firewall policy(DROP INPUT)
      - 3.5.1.4 # Ensure firewall rules exist for accepting SSH connections
      - 3.5.2.1 # Ensure IPv6 default deny firewall policy

    cis_level_2_exclusions:
      - 1.6.1.1 # Install and ensure SELinux is not disabled 
      - 1.6.1.2 # Setup selinux
      - 1.6.1.3 # Setup selinux
      - 1.6.1.4 # Ensure SETroubleshoot is not installed (Scored)
      - 1.6.1.5 # not applicable because mcstrans is part of SELinux
      - 1.6.2   # Install the SE Linux requirements - libselinux
      - 3.6     # Ensure that IPv6 is disabled (docker run --sysctl net.ipv4.ip_forward=1 someimage)
      #- 4.1.1.2 # Ensure system is disabled when audit logs are full - auditd
      #- 4.1.2   # Ensure auditd service is enabled (Scored) - auditd
      - 4.1.3   # Update grub with audit enabled - auditd
      # - 4.1.4   # Ensure events that modify date and time information are collected (Scored) - auditd
      # - 4.1.5   # Ensure events that modify user/group information are collected(Scored) - auditd
      # - 4.1.6   # Ensure events that modify the system's network environment are collected(Scored) - auditd
      # - 4.1.7   # Ensure events that modify the system's Mandatory Access Controls are collected(Scored) - auditd
      # - 4.1.8   # Ensure login and logout events are collected(Scored) - auditd
      # - 4.1.9   # Ensure session initiation information is collected (Scored) - auditd
      # - 6.1.1   # Audit system file permissions 


  roles:
    - AmazonLinux2-Hardening-Ansible


# Dcoker issues:
# - Problems with SystemD in Docker - https://github.com/gdraheim/docker-systemctl-replacement
# - AuditD missing container support - https://capsule8.com/blog/auditd-what-is-the-linux-auditing-system/, https://stackoverflow.com/questions/53311314/error-running-auditd-inside-centos-docker-container-unable-to-set-initial-audi, https://devops.stackexchange.com/questions/6445/process-auditing-in-containers, https://medium.com/@rhonnava/audit-logging-with-container-id-tagging-65e92c570f12
# - Docker does not support changing sysctls inside of a container ( --sysctl net.ipv6.conf.all.disable_ipv6=1) - https://docs.docker.com/engine/reference/commandline/run/
# - SELinux disabled inside of a Docker container - https://serverfault.com/questions/757606/how-to-enable-selinux-inside-of-a-centos-docker-container, https://serverfault.com/questions/632643/how-should-i-configure-selinux-when-running-nginx-inside-docker
